# Generated by Django 2.1.2 on 2019-01-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
