# Generated by Django 2.1.2 on 2019-01-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0003_auto_20190123_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
